on: [push]

jobs:
  package_maintenance_job:
    runs-on: ubuntu-latest
    name: A job to check Maven's project dependencies maintenance
    steps:
      - name: package-maintenance
        id: package-maintenance
        uses: package-maintenance-dev/github-action@v0.0.1-SNAPSHOT
